development: 
  adapter : postgresql
  database: mp_development
  encoding: unicode
  pool: 5


test: 
  adapter : postgresql
  database: mp_test
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: mp_production
  pool: 5